# Generated by Django 2.0.4 on 2018-04-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APKFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('package_name', models.CharField(blank=True, max_length=200)),
                ('package_version_code', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
